url: https://y7kim.github.io

# Site settings
title: Nicole Tufts
email: ntufts1025@gmail.com
description: "Everyone has a story to tell. Some of the most interesting stories come from those you would least expect it. My goal is to uncover these hidden stories in hopes giving a voice to those who deserve to be heard but struggle to do so."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FFB2B2
  secondary: F09797
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://www.instagram.com/nicole_1025/
  - title: facebook
    url: http://www.facebook.com/nicole.tufts
  - title: linkedin
    url: http://www.linkedin.com/in/nicole-tufts-49b816100

# Build settings
markdown: kramdown
permalink: pretty
